version: '3.9'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.11.1
    ports:
      - "9201:9200"
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - elasticNetwork
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    container_name: kibana
    image: kibana:8.11.1
    ports:
      - "5602:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_HOSTS: 0.0.0.0
    networks:
      - elasticNetwork
    depends_on:
      - elasticsearch
    volumes:
      - data:/usr/share/elasticsearch/data
  logstash:
    container_name: logstash
    image: logstash:8.11.1
    ports:
      - "5045:5044"
      - "9601:9600"
    environment:
      - xpack.monitoring.enabled=false
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_HOSTS=0.0.0.0
    depends_on:
      - kibana
    networks:
      - elasticNetwork
networks:
  elasticNetwork:
    driver: bridge
volumes:
  data:
    driver: local
